#!/bin/bash
SOCKETS=$(ssh -q $1 'lscpu | grep "Socket(s):"  | cut -d : -f 2 | sed "s/ //g"')
THREADSPERCORE=$(ssh -q $1 'lscpu | grep "Thread(s) per core:" | cut -d : -f 2 | sed "s/ //g"')
CORESPERSOCKET=$(ssh -q $1 'lscpu | grep "Core(s) per socket:" | cut -d : -f 2 | sed "s/ //g"')
COUNT="0"
echo "Add lines between --- to gres.conf:"
echo "---"
for i in $(ssh -q $1 'lspci | grep -i nvidia | grep -v Audio | sed "s/ //g" | cut -d : -f 1')
        do
	CPUAFFINITY=$(ssh -q $1 "cat /sys/class/pci_bus/0000:$i/cpulistaffinity")
        echo "NodeName=$(ssh -q $1 'cat /etc/hostname') Name=gpu File=/dev/nvidia"$COUNT" CPUs=$CPUAFFINITY"
        ((COUNT++))
        done

echo "---"
echo ""
echo "Add line to end of slurm.conf:"
echo "NodeName=$(ssh -q $1 'cat /etc/hostname') Gres=gpu:$COUNT Sockets=$SOCKETS CoresPerSocket=$CORESPERSOCKET ThreadsPerCore=$THREADSPERCORE State=UNKNOWN"

echo ""
echo "Using slurmd -C:"
#ssh -q $1 "slurmd -C | head -n 1"
RFIRST=$(ssh -q $1 "slurmd -C | cut -f1 -d' ' --complement | head -n 1")
echo "NodeName=$(ssh -q $1 'cat /etc/hostname') $RFIRST"
